// api/generate.js - Vercel Serverless Function
import fetch from "node-fetch";

export default async function handler(req, res) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Credentials', true);
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight request
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { occasion, recipient, budget, style, notes, previouslyShown } = req.body;
    
    // Get API key from environment variable
    const API_KEY = process.env.GEMINI_API_KEY;
    
    if (!API_KEY) {
      return res.status(500).json({ error: 'API key not configured' });
    }

    // Build the prompt with exclusions
    let prompt = `Suggest exactly 3 unique and creative gift ideas within ₹${budget} for a ${recipient} during ${occasion}. Style preference: ${style}.`;
    
    if (notes) {
      prompt += ` Additional notes: ${notes}.`;
    }
    
    // Add exclusion list if provided
    if (previouslyShown && previouslyShown.length > 0) {
      prompt += `\n\nIMPORTANT: DO NOT suggest any of these gifts that were already shown: ${previouslyShown.join(', ')}. Provide completely different alternatives.`;
    }

    prompt += `\n\nIMPORTANT FORMATTING:
- Gift names: Keep short and catchy (maximum 8-10 words)
- Explanations: Brief and punchy (maximum 25-30 words, 1-2 sentences)
- Be concise but meaningful

Provide fresh, thoughtful suggestions that feel personal and intentional.`;

    console.log("Generating with prompt:", prompt);
    console.log("Excluding:", previouslyShown || "none");

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${API_KEY}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            response_mime_type: "application/json",
            response_schema: {
              type: "object",
              properties: {
                gifts: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      gift: { type: "string" },
                      why: { type: "string" },
                      price_range: { type: "string" }
                    },
                    required: ["gift", "why", "price_range"]
                  }
                }
              },
              required: ["gifts"]
            }
          }
        })
      }
    );

    const data = await response.json();

    // Error handling
    if (data.error) {
      console.error("Gemini API Error:", data.error.message);
      return res.status(data.error.code || 400).json({ error: data.error.message });
    }

    if (!data.candidates || !data.candidates[0].content.parts[0].text) {
      throw new Error("No content generated by Gemini");
    }

    // Parse the JSON response
    const resultText = data.candidates[0].content.parts[0].text;
    const parsedResult = JSON.parse(resultText);
    
    console.log("Generated gifts:", parsedResult.gifts.map(g => g.gift));
    
    res.json(parsedResult);

  } catch (err) {
    console.error("SERVER ERROR:", err);
    res.status(500).json({ error: "Gift generation failed", message: err.message });
  }
}